name: continuous-integration-gate
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: '24'
      - name: install
        run: npm ci
      - name: ESLint
        run: npm run lint:check
      - name: ESLint
        run: npm run prettier:check
